/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.*;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author juan
 */
public class Menu extends javax.swing.JFrame {

    
    
    /**
     * @return the nfac
     */
    public NuevaFactura getNfac() {
        return nfac;
    }

    /**
     * @param nfac the nfac to set
     */
    public void setNfac(NuevaFactura nfac) {
        this.nfac = nfac;
    }

    /**
     * Creates new form Menu
     */
     public Menu(String Usuario) throws SQLException{
        this.setUndecorated(true);
        initComponents();
        Setnameoflabels();
        cargarMenu(Usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jControlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jblVisitas = new javax.swing.JButton();
        jblCroquis = new javax.swing.JButton();
        jblResidentes = new javax.swing.JButton();
        jblFactura = new javax.swing.JButton();
        jblMembresia = new javax.swing.JButton();
        jblDueno = new javax.swing.JButton();
        jblVivienda = new javax.swing.JButton();
        jblRegistro = new javax.swing.JButton();
        jblCerrar = new javax.swing.JLabel();
        jblMinimizar = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/interfaz-de-hogar.png"))); // NOI18N
        jButton7.setToolTipText("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/anadir.png"))); // NOI18N
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jControlPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.PNG"))); // NOI18N

        jblVisitas.setBackground(new java.awt.Color(255, 255, 255));
        jblVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Visi1.png"))); // NOI18N
        jblVisitas.setBorder(null);
        jblVisitas.setOpaque(false);
        jblVisitas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Visi.png"))); // NOI18N
        jblVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVisitasMouseClicked(evt);
            }
        });

        jblCroquis.setBackground(new java.awt.Color(255, 255, 255));
        jblCroquis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Croquis1.png"))); // NOI18N
        jblCroquis.setBorder(null);
        jblCroquis.setOpaque(false);
        jblCroquis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Croquis.png"))); // NOI18N
        jblCroquis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblCroquisActionPerformed(evt);
            }
        });

        jblResidentes.setBackground(new java.awt.Color(255, 255, 255));
        jblResidentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Resi1.png"))); // NOI18N
        jblResidentes.setBorder(null);
        jblResidentes.setOpaque(false);
        jblResidentes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Resi.png"))); // NOI18N
        jblResidentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblResidentesMouseClicked(evt);
            }
        });

        jblFactura.setBackground(new java.awt.Color(255, 255, 255));
        jblFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Factu1.png"))); // NOI18N
        jblFactura.setBorder(null);
        jblFactura.setOpaque(false);
        jblFactura.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Factu.png"))); // NOI18N
        jblFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblFacturaMouseClicked(evt);
            }
        });

        jblMembresia.setBackground(new java.awt.Color(255, 255, 255));
        jblMembresia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Membre1.png"))); // NOI18N
        jblMembresia.setBorder(null);
        jblMembresia.setOpaque(false);
        jblMembresia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Membre.png"))); // NOI18N
        jblMembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblMembresiaMouseClicked(evt);
            }
        });

        jblDueno.setBackground(new java.awt.Color(255, 255, 255));
        jblDueno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Due1.png"))); // NOI18N
        jblDueno.setBorder(null);
        jblDueno.setOpaque(false);
        jblDueno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Due.png"))); // NOI18N
        jblDueno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblDuenoMouseClicked(evt);
            }
        });

        jblVivienda.setBackground(new java.awt.Color(255, 255, 255));
        jblVivienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Regis1.png"))); // NOI18N
        jblVivienda.setBorder(null);
        jblVivienda.setOpaque(false);
        jblVivienda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Regis.png"))); // NOI18N

        jblRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jblRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Regis1.png"))); // NOI18N
        jblRegistro.setBorder(null);
        jblRegistro.setOpaque(false);
        jblRegistro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Palabras/Regis.png"))); // NOI18N
        jblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblRegistroMouseClicked(evt);
            }
        });

        jblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/borrar (1).png"))); // NOI18N
        jblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCerrarMouseClicked(evt);
            }
        });

        jblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar (5).png"))); // NOI18N
        jblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jControlPanelLayout = new javax.swing.GroupLayout(jControlPanel);
        jControlPanel.setLayout(jControlPanelLayout);
        jControlPanelLayout.setHorizontalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jControlPanelLayout.createSequentialGroup()
                        .addComponent(jblVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblCroquis, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblResidentes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(484, 484, 484))
                    .addGroup(jControlPanelLayout.createSequentialGroup()
                        .addComponent(jblMinimizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblCerrar)
                        .addGap(474, 474, 474)))
                .addComponent(jblVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jControlPanelLayout.setVerticalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblVivienda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblMinimizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblCerrar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblVisitas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblCroquis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblResidentes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblFactura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblMembresia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblDueno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblRegistro, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        getContentPane().add(jControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jDesktopPane1.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, -40, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }
Vivienda v = new Vivienda(); Dueno d = new Dueno(); Fresidentes fr = new Fresidentes();  FrVisitas f=new FrVisitas();
Membresias mb = new Membresias(); Registrar r=new Registrar(); private NuevaFactura nfac = new NuevaFactura();Facturas fac = new Facturas(this);

    public void limpiarformularios(){
        v.dispose(); d.dispose(); fr.dispose();mb.dispose(); f.dispose(); r.dispose();fac.dispose();nfac.dispose();
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.limpiarformularios();
        v = new Vivienda();
       this.jDesktopPane1.add(v);v.setVisible(true);v.show();
      int x =(this.jDesktopPane1.getWidth()/2)-v.getWidth()/2;
      int y =(this.jDesktopPane1.getWidth()/2)-v.getWidth()/2;
      v.setLocation(x,y);v.setTitle("VIVIENDAS");
        try{
       // v.setMaximum(true);
     
    }catch(Exception ex){}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jblCroquisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblCroquisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblCroquisActionPerformed

    private void jblFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblFacturaMouseClicked
        // TODO add your handling code here:
        
        this.limpiarformularios();
        fac.llenarTabla();
        this.jDesktopPane1.removeAll();
         this.jDesktopPane1.add(fac);
         fac.setVisible(true);
         fac.setTitle("FACTURAS");
         fac.show();
    }//GEN-LAST:event_jblFacturaMouseClicked

    private void jblDuenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDuenoMouseClicked
        // TODO add your handling code here:
         this.limpiarformularios();
        d = new Dueno();this.jDesktopPane1.add(d);d.setVisible(true);
        
    }//GEN-LAST:event_jblDuenoMouseClicked

    private void jblResidentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblResidentesMouseClicked
        // TODO add your handling code here:
        this.limpiarformularios();
        fr = new Fresidentes();this.jDesktopPane1.add(fr);fr.setVisible(true);
    }//GEN-LAST:event_jblResidentesMouseClicked

    private void jblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRegistroMouseClicked
        // TODO add your handling code here:
        this.limpiarformularios();
        r=new Registrar();this.jDesktopPane1.add(r);r.setVisible(true);
       
    }//GEN-LAST:event_jblRegistroMouseClicked

    private void jblVisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVisitasMouseClicked
        // TODO add your handling code here:
        this.limpiarformularios();
        f = new FrVisitas();this.jDesktopPane1.add(f);f.setVisible(true);
    }//GEN-LAST:event_jblVisitasMouseClicked

    private void jblMembresiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblMembresiaMouseClicked
        // TODO add your handling code here:
        this.limpiarformularios();
        mb= new Membresias();this.jDesktopPane1.add(mb);mb.setVisible(true);
    }//GEN-LAST:event_jblMembresiaMouseClicked

    private void jblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(Formularios.Login1.ICONIFIED);
    }//GEN-LAST:event_jblMinimizarMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCerrarMouseClicked
        // TODO add your handling code here:
        try{
          int dialogButton=JOptionPane.YES_NO_OPTION;
          int result= JOptionPane.showConfirmDialog(this, "Seguro que desea salir","EXIT",dialogButton);
          if(result==0){
              System.exit(0);
          }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jblCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                try {
                    new Menu(" ").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jControlPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jblCerrar;
    private javax.swing.JButton jblCroquis;
    private javax.swing.JButton jblDueno;
    private javax.swing.JButton jblFactura;
    private javax.swing.JButton jblMembresia;
    private javax.swing.JLabel jblMinimizar;
    private javax.swing.JButton jblRegistro;
    private javax.swing.JButton jblResidentes;
    private javax.swing.JButton jblVisitas;
    private javax.swing.JButton jblVivienda;
    // End of variables declaration//GEN-END:variables

 private void cargarMenu(String Users) throws SQLException {
        Conexion cn= new Conexion ();
        ArrayList<String> t=new ArrayList<String>();
        t =DAL.executeSprocInParams(cn.conectar(), DAL.GetRolId(Conexion.getConexion(), Users));
        for(int i=0; i<t.size();i++){
            Component[] indice = jControlPanel.getComponents();
            for(int j=0;j<jControlPanel.getComponents().length;j++){
            if(t.get(i).equals(jControlPanel.getComponent(j).getName())){
                jControlPanel.getComponent(j).setVisible(true);
            }
            }
        }
//            for(String i : t){
//                for(Component j:jControlPanel.getComponents()){
//                    if(j.getName()!=null){
//                    if(i.trim().equals(j.getName().trim())){
//                        j.setVisible(true);
//                    }
//                    }
//                }
//            }

        
    }

    private void Setnameoflabels() {
         jblCroquis.setName("jblCroquis");
    jblFactura.setName("jblFactura");
    jblMembresia.setName("jblMembresia");
  jblRegistro.setName("jblRegistro");
 jblResidentes.setName("jblResidente");
       jblVisitas.setName("jblVisitas");
   jblVivienda.setName("jblVivienda");
      jblCroquis.setVisible(false);
    jblFactura.setVisible(false);
    jblMembresia.setVisible(false);
  jblRegistro.setVisible(true);
 jblResidentes.setVisible(false);
       jblVisitas.setVisible(true);
   jblVivienda.setVisible(true);
//   jpNuevaFactura.setVisible(false);
    }
}

